### ISSUE TITLE
repaint memo / app_idle

### ISSUE THREAD

**Issue by veksha** [CudaText-addons/cuda_testing_attr#1]
```
#we can repaint memo every iteration here, but...
#self.memo.action(EDACTION_UPDATE) # not repainting markers it seems.
#app_idle() # repaints, but if I hold key it causes recursion into "form_key_press"?? how to avoid it?
```

can you, @Alexey-T, comment on these lines?
How to repaint correctly? (ExTerminal also has issues like this, hold a key and repaint is not happening, until you release it)

**Comment by Alexey-T** [comment]
formmain_py_api.inc
find 
```
case IdAction of
        EDACTION_UPDATE:
```
and change code to
```
      case IdAction of
        EDACTION_UPDATE:
          begin
            Ed.Update(
              AppStrToBool(StrText1),
              true
              );
            Result:= ReturnNone;
          end; 
```
it helps?

**Comment by Alexey-T** [comment]
@veksha

**Comment by veksha** [comment]
@Alexey-T No, sorry for delay.

**Comment by veksha** [comment]
this is what I expect:

https://user-images.githubusercontent.com/275333/178070069-441ff241-2e1e-4268-a6da-3e32de9b49e3.mp4

**Comment by veksha** [comment]
i'm testing on Windows. maybe it works for Linux?

**Comment by Alexey-T** [comment]
it's not so even on Linnux.
1. BTW, can you prevent recursive entering (by using bool variable) and use app_idle?

**Comment by Alexey-T** [comment]
2. maybe call `Ed.Invalidate` will help in the code? in the handler of EDACtiON_UPDATE.

 I am on dacha and I have only small/poor Win10 notebook which i don't like to use, and good notebook with linux (i use it).

**Comment by veksha** [comment]
1. I will try it. Thanks for this hint.
2. Ed.Repaint helps in EDACTION_UPDATE!

**Comment by Alexey-T** [comment]
2. applied, tks. only for windows. (I don't seee effect on GTK2.)

**Comment by veksha** [comment]
tried `bool var + app_idle`. works too!
slower then Ed.Repaint, but has other advantages (like you can hold keyboard key and select with mouse at the same time, for example, because all of the messages are processed, obviously).

>  applied, tks. only for windows. (I don't seee effect on GTK2.)

cool!
